/**
 * Account model
 *
 * Represents a user's Futures or CFD account.
 *
 * The account itself stores the account rules/configuration.
 * Individual journal trades are connected separately through
 * account_trade_attachments.
 */

export type AccountType = 'futures' | 'cfd';

export type AccountRuleMode = 'standard' | 'custom';

export type FuturesPhase = 'evaluation' | 'funded';

export type CfdPhase = 'phase1' | 'phase2' | 'funded';

export type AccountPhase = FuturesPhase | CfdPhase;

export type AccountResult = 'active' | 'passed' | 'failed';

export interface Account {
  /** Supabase account UUID */
  id: string;

  /** Supabase auth user UUID */
  userId: string;

  /** User-defined account name */
  name: string;

  /** Futures or CFD */
  accountType: AccountType;

  /** Account phase in prop-firm lifecycle */
  phase: AccountPhase;

  /** Account result/outcome */
  result: AccountResult;

  /** Account size, e.g. 25000, 50000, 5000 */
  accountSize: number;

  /** Standard industry/account rules or user customization */
  ruleMode: AccountRuleMode;

  /** Profit target in account currency */
  profitTarget: number | null;

  /** Maximum allowed drawdown in account currency */
  maxDrawdown: number | null;

  /** Account creation timestamp */
  createdAt: string;

  /** Last account update timestamp */
  updatedAt: string;
}

/**
 * Data required when creating a new account.
 *
 * id, userId and timestamps are generated by the database/app.
 */
export interface CreateAccountInput {
  name: string;
  accountType: AccountType;
  phase: AccountPhase;
  result?: AccountResult;
  accountSize: number;
  ruleMode: AccountRuleMode;

  profitTarget?: number | null;
  maxDrawdown?: number | null;
}

/**
 * Data that can be changed after an account has been created.
 */
export interface UpdateAccountInput {
  name?: string;
  accountType?: AccountType;
  accountSize?: number;
  phase?: AccountPhase;
  result?: AccountResult;
  ruleMode?: AccountRuleMode;

  profitTarget?: number | null;
  maxDrawdown?: number | null;
}